// Rich Realistic Production Seed Dataset for CivicEye-AI
const seedReports = [
  {
    _id: "ce_seed_101",
    id: "ce_seed_101",
    ticketId: "CE-2609-A8F29B",
    title: "Deep Pothole on Main Arterial Road (West High Court Rd)",
    description: "Substantial 4-inch deep asphalt crater on the right carriage lane near Coffee House Square signal. Causing severe two-wheeler skidding risk and traffic slowdown during evening rush hours.",
    category: "Pothole & Road Damage",
    subcategory: "Severe Asphalt Crater",
    severityScore: 8.8,
    urgencyLevel: "CRITICAL",
    aiConfidence: 0.96,
    aiRawAnalysis: {
      detectedCategory: "Pothole & Road Damage",
      severityScore: 8.8,
      urgencyLevel: "CRITICAL",
      confidence: 0.96,
      recommendedDepartment: "Public Works & Roads (PWD)",
      keyHazards: ["Two-wheeler skidding risk", "Vehicular tyre & rim damage", "Traffic bottleneck"],
    },
    status: "IN_PROGRESS",
    assignedDepartment: "Public Works & Roads (PWD)",
    assignedOfficer: "Er. Rajesh Verma (Executive Engineer, PWD Div II)",
    officerContact: "+91 94221 34910",
    resolutionNotes: "Crew dispatched with hotmix asphalt patch unit & pneumatic roller. 80% resurfacing complete.",
    resolutionImageUrl: "",
    latitude: 21.1458,
    longitude: 79.0882,
    address: "West High Court Road, Dharampeth",
    landmark: "Near Coffee House Square & Shankar Nagar Metro",
    wardNumber: "Ward 12 - Dharampeth",
    zoneName: "Zone 2 (West)",
    imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80",
    reporterName: "Ananya Sharma",
    reporterPhone: "+91 98230 44120",
    reporterEmail: "ananya.sharma@gmail.com",
    upvotes: 27,
    upvotedBy: ["guest_1", "guest_2", "guest_3", "guest_10", "guest_11"],
    isDuplicate: false,
    duplicateOfTicketId: null,
    estimatedSlaHours: 24,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    comments: [
      {
        userName: "Rahul Tiwari (Local Resident)",
        userRole: "RESIDENT",
        text: "Almost had an accident here yesterday night on my scooter. Please fix immediately!",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
      },
      {
        userName: "Er. Rajesh Verma (PWD Officer)",
        userRole: "OFFICER",
        text: "Patching crew team #4 is on-site. Work will be concluded by 5:00 PM today.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      },
    ],
    timelineEvents: [
      {
        status: "REPORTED",
        title: "Complaint Registered via Citizen Mobile Portal",
        description: "Ticket CE-2609-A8F29B logged. Citizen submitted geotagged photo.",
        actorName: "Ananya Sharma",
        actorRole: "CITIZEN",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      },
      {
        status: "VERIFIED",
        title: "AI Triage Verification Completed",
        description: "Vision AI assessed severity as 8.8 (CRITICAL). Auto-routed to PWD Roads Division.",
        actorName: "CivicEye AI Engine",
        actorRole: "SYSTEM",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 17).toISOString(),
      },
      {
        status: "ASSIGNED",
        title: "Work Order Issued to Field Officer",
        description: "Assigned to Er. Rajesh Verma (Executive Engineer, PWD Div II).",
        actorName: "Municipal Control Room",
        actorRole: "ADMIN",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
      },
      {
        status: "IN_PROGRESS",
        title: "Hotmix Patching Crew Deployed On-Site",
        description: "Asphalt cutter, cold emulsion binder, and roller crew active.",
        actorName: "Er. Rajesh Verma",
        actorRole: "OFFICER",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      },
    ],
  },
  {
    _id: "ce_seed_102",
    id: "ce_seed_102",
    ticketId: "CE-2609-C39E11",
    title: "Overflowing Commercial Waste Dumpster & Footpath Encroachment",
    description: "Primary municipal bin overflowing with organic & commercial plastic waste. Scatter is blocking 60% of the pedestrian sidewalk creating heavy odor and stray animal gathering.",
    category: "Garbage & Sanitation",
    subcategory: "Commercial Bin Spillover",
    severityScore: 7.2,
    urgencyLevel: "HIGH",
    aiConfidence: 0.93,
    aiRawAnalysis: {
      detectedCategory: "Garbage & Sanitation",
      severityScore: 7.2,
      urgencyLevel: "HIGH",
      confidence: 0.93,
      recommendedDepartment: "Solid Waste Management",
      keyHazards: ["Bacterial contamination", "Footpath blockage", "Odor pollution"],
    },
    status: "ASSIGNED",
    assignedDepartment: "Solid Waste Management",
    assignedOfficer: "Sanitation Supervisor Sanjay Patil",
    officerContact: "+91 97650 88219",
    resolutionNotes: "Assigned to Compactor Truck Route #7 (Sadar Morning Shift).",
    resolutionImageUrl: "",
    latitude: 21.1524,
    longitude: 79.0805,
    address: "Residency Road, Sadar Bazar",
    landmark: "Opposite Rajwada Palace Gate, Near Sadar Police Chowki",
    wardNumber: "Ward 15 - Sadar",
    zoneName: "Zone 1 (Central)",
    imageUrl: "https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?w=800&auto=format&fit=crop&q=80",
    reporterName: "Rohan Deshmukh",
    reporterPhone: "+91 97654 11290",
    reporterEmail: "rohan.d@yahoo.com",
    upvotes: 19,
    upvotedBy: ["guest_4", "guest_5", "guest_6"],
    isDuplicate: false,
    duplicateOfTicketId: null,
    estimatedSlaHours: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    comments: [
      {
        userName: "Meena Agrawal (Shop Owner)",
        userRole: "RESIDENT",
        text: "The smell is entering nearby eateries. Please clear before lunch hours.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
      },
    ],
    timelineEvents: [
      {
        status: "REPORTED",
        title: "Citizen Filed Sanitation Complaint",
        description: "Garbage accumulation photo submitted with GPS tag.",
        actorName: "Rohan Deshmukh",
        actorRole: "CITIZEN",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      },
      {
        status: "ASSIGNED",
        title: "Work Order Dispatched to Zone 1 Compactor Unit",
        description: "Assigned to Supervisor Sanjay Patil.",
        actorName: "NMC Sanitation Desk",
        actorRole: "ADMIN",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      },
    ],
  },
  {
    _id: "ce_seed_103",
    id: "ce_seed_103",
    ticketId: "CE-2609-F91A80",
    title: "Broken Streetlight & Exposed Electrical Junction Box",
    description: "Bent octagonal streetlight pole with missing inspection door exposing 415V cables at 3-foot height. Total darkness over a 50m residential stretch.",
    category: "Streetlight & Electrical",
    subcategory: "Exposed High-Voltage Cable",
    severityScore: 9.2,
    urgencyLevel: "CRITICAL",
    aiConfidence: 0.98,
    aiRawAnalysis: {
      detectedCategory: "Streetlight & Electrical",
      severityScore: 9.2,
      urgencyLevel: "CRITICAL",
      confidence: 0.98,
      recommendedDepartment: "Electricity & Street Lighting",
      keyHazards: ["Electrocution risk", "Low nocturnal visibility", "Structural collapse of pole"],
    },
    status: "RESOLVED",
    assignedDepartment: "Electricity & Street Lighting",
    assignedOfficer: "Junior Engineer K. Nair (MSEDCL/NMC Electrical)",
    officerContact: "+91 94231 10984",
    resolutionNotes: "Pole structure re-anchored, electrical junction box insulated with heavy-duty IP65 lock, new 90W LED luminaire commissioned. Fully tested and safe.",
    resolutionImageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    latitude: 21.1402,
    longitude: 79.0734,
    address: "Temple Road, Civil Lines",
    landmark: "Behind Bombay High Court Nagpur Bench, Gate 3",
    wardNumber: "Ward 14 - Civil Lines",
    zoneName: "Zone 2 (West)",
    imageUrl: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=800&auto=format&fit=crop&q=80",
    reporterName: "Adv. Pooja Kulkarni",
    reporterPhone: "+91 94221 88301",
    reporterEmail: "pooja.law@gmail.com",
    upvotes: 42,
    upvotedBy: ["guest_1", "guest_2", "guest_7", "guest_8", "guest_9"],
    isDuplicate: false,
    duplicateOfTicketId: null,
    estimatedSlaHours: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    comments: [
      {
        userName: "Adv. Pooja Kulkarni (Citizen)",
        userRole: "CITIZEN",
        text: "Thank you for the super fast repair! The street is fully illuminated now and cables are secured.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
      },
    ],
    timelineEvents: [
      {
        status: "REPORTED",
        title: "Hazardous Live Wire Reported",
        description: "Citizen reported open electrical box near sidewalk.",
        actorName: "Adv. Pooja Kulkarni",
        actorRole: "CITIZEN",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
      },
      {
        status: "IN_PROGRESS",
        title: "Emergency Line Crew Dispatched",
        description: "Feeder shut-off approved. Electrical repair crew arrived on site.",
        actorName: "MSEDCL Electrical Board",
        actorRole: "OFFICER",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      },
      {
        status: "RESOLVED",
        title: "AI Resolution Inspection Verified & Closed",
        description: "After-photo verified. 90W LED luminaire operational. Nodal officer signed off.",
        actorName: "CivicEye AI Inspector",
        actorRole: "SYSTEM",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
      },
    ],
  },
  {
    _id: "ce_seed_104",
    id: "ce_seed_104",
    ticketId: "CE-2609-B52D44",
    title: "Stormwater Drain Choke & Road Inundation (Sitabuldi)",
    description: "Clogged stormwater inlet grating filled with silt and single-use plastic waste. Causing 8-inch stagnant road flooding at the Variety Square intersection.",
    category: "Waterlogging & Drainage",
    subcategory: "Storm Drain Clogging",
    severityScore: 8.5,
    urgencyLevel: "HIGH",
    aiConfidence: 0.94,
    aiRawAnalysis: {
      detectedCategory: "Waterlogging & Drainage",
      severityScore: 8.5,
      urgencyLevel: "HIGH",
      confidence: 0.94,
      recommendedDepartment: "Water Supply & Sewerage Board",
      keyHazards: ["Mosquito breeding ground", "Vehicular engine stalling", "Road sub-base erosion"],
    },
    status: "REPORTED",
    assignedDepartment: "Water Supply & Sewerage Board",
    assignedOfficer: "Duty Nodal Officer (Drainage Div)",
    officerContact: "+91 712-2561122",
    resolutionNotes: "",
    resolutionImageUrl: "",
    latitude: 21.1345,
    longitude: 79.0851,
    address: "Sitabuldi Main Road",
    landmark: "Near Variety Square Metro Station Pillar 142",
    wardNumber: "Ward 18 - Sitabuldi",
    zoneName: "Zone 1 (Central)",
    imageUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80",
    reporterName: "Vikram Joshi",
    reporterPhone: "+91 99220 77154",
    reporterEmail: "vikram.joshi@outlook.com",
    upvotes: 16,
    upvotedBy: ["guest_3", "guest_12"],
    isDuplicate: false,
    duplicateOfTicketId: null,
    estimatedSlaHours: 24,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    comments: [],
    timelineEvents: [
      {
        status: "REPORTED",
        title: "Waterlogging Complaint Filed",
        description: "Citizen reported intersection flooding with photo evidence.",
        actorName: "Vikram Joshi",
        actorRole: "CITIZEN",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      },
    ],
  },
  {
    _id: "ce_seed_105",
    id: "ce_seed_105",
    ticketId: "CE-2609-E77A19",
    title: "Fallen Tree Bough Blocking Left Lane on Medical College Road",
    description: "Heavy branch snapped from aged Banyan tree during squall. Spanning across the left traffic lane leading to Government Medical College & Hospital emergency ward.",
    category: "Road Obstruction & Traffic",
    subcategory: "Fallen Tree Limb",
    severityScore: 8.1,
    urgencyLevel: "HIGH",
    aiConfidence: 0.95,
    aiRawAnalysis: {
      detectedCategory: "Road Obstruction & Traffic",
      severityScore: 8.1,
      urgencyLevel: "HIGH",
      confidence: 0.95,
      recommendedDepartment: "Horticulture & Forestry",
      keyHazards: ["Emergency ambulance obstruction", "Collision risk for high-speed vehicles"],
    },
    status: "IN_PROGRESS",
    assignedDepartment: "Horticulture & Forestry",
    assignedOfficer: "Forestry Squad Leader Ramesh Gawande",
    officerContact: "+91 98812 44331",
    resolutionNotes: "Chainsaw crew deployed. Trunk sectioned into manageable logs. Crane crane loading underway.",
    resolutionImageUrl: "",
    latitude: 21.1278,
    longitude: 79.0965,
    address: "Medical College Road, Ajni Ward",
    landmark: "Near GMC Hostel Gate 2 & Trauma Center",
    wardNumber: "Ward 22 - Medical",
    zoneName: "Zone 4 (South)",
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80",
    reporterName: "Dr. Snehal Tandale",
    reporterPhone: "+91 98810 55432",
    reporterEmail: "dr.snehal@gmch.org",
    upvotes: 31,
    upvotedBy: ["guest_1", "guest_8", "guest_14"],
    isDuplicate: false,
    duplicateOfTicketId: null,
    estimatedSlaHours: 6,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    comments: [
      {
        userName: "GMC Ambulance Dispatch",
        userRole: "OFFICER",
        text: "Priority clearance requested as ambulances are being rerouted.",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      },
    ],
    timelineEvents: [
      {
        status: "REPORTED",
        title: "Obstruction Reported by Medical Staff",
        description: "Emergency lane obstruction flagged.",
        actorName: "Dr. Snehal Tandale",
        actorRole: "CITIZEN",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      },
      {
        status: "IN_PROGRESS",
        title: "Emergency Forestry Squad Mobilized",
        description: "Hydraulic chainsaw unit and loader truck dispatched.",
        actorName: "NMC Garden & Tree Authority",
        actorRole: "OFFICER",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
      },
    ],
  },
];

module.exports = {
  seedReports,
};
